language: rust

# Need to cache the whole `.cargo` directory to keep .crates.toml for
# cargo-update to work
#
cache:
  directories:
    - /home/travis/.cargo

# But don't cache the cargo registry
# and remove wasm-pack binary to avoid the installer asking confirmation for overwriting it.
#
before_cache:
  - rm -rfv /home/travis/.cargo/git
  - rm -rfv /home/travis/.cargo/registry
  - rm -rfv /home/travis/.cargo/bin/cargo-tarpaulin
  - rm -rfv target/debug/incremental/{{{crate_name}},build_script_build}-*
  - rm -rfv target/debug/.fingerprint/{{crate_name}}-*
  - rm -rfv target/debug/build/{{crate_name}}-*
  - rm -rfv target/debug/deps/lib{{crate_name}}-*
  - rm -rfv target/debug/deps/{{crate_name}}-*
  - rm -rfv target/debug/{{{crate_name}},lib{{crate_name}}}.d
  - cargo clean -p {{crate_name}}

branches:
  only:
    - master
    - dev

jobs:

  include:

    - name: linux stable rust
      os  : linux
      rust: stable

      script:
        - bash ci/test.bash


    - name: linux nightly rust
      os  : linux
      dist: bionic # required for tarpaulin binary distribution to work.
      rust: nightly

      addons:
        apt:
          packages:
            - libssl-dev # for cargo-tarpaulin


      script:
        - bash ci/test.bash
        - bash ci/doc.bash
        - bash ci/coverage.bash


    - name: osx stable rust
      os  : osx
      rust: stable

      script:
        - bash ci/test.bash


    - name: windows stable rust
      os  : windows
      rust: stable

      script:
        - bash ci/test.bash





